//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hafta7
{
    using System;
    using System.Collections.Generic;
    
    public partial class User2
    {
        public int U_id { get; set; }
        public string U_name { get; set; }
        public string U_surName { get; set; }
        public string U_address { get; set; }
        public string U_phone { get; set; }
        public string U_email { get; set; }
        public string U_degree { get; set; }
        public string U_experience { get; set; }
        public string U_language { get; set; }
        public string U_Education { get; set; }
        public string U_password { get; set; }
        public string U_dateofBirth { get; set; }
    }
}
